#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_MAIN="$ROOT_DIR/mediarr-card.main.js"
OUTPUT_FILE="$ROOT_DIR/mediarr-card.js"

MODULES=(
  "base-section.js"
  "plex-section.js"
  "jellyfin-section.js"
  "sonarr-section.js"
  "sonarr2-section.js"
  "radarr-section.js"
  "radarr2-section.js"
  "seer-section.js"
  "tmdb-section.js"
  "trakt-section.js"
  "immaculaterr-section.js"
  "styles.js"
)

TMP_FILE="$(mktemp)"

if [[ ! -f "$SOURCE_MAIN" ]]; then
  echo "Missing source file: $SOURCE_MAIN" >&2
  exit 1
fi

{
  echo "// mediarr-card.js (single-file build for HACS)"
  echo "// Generated by scripts/build-single-file.sh"

  for module in "${MODULES[@]}"; do
    module_path="$ROOT_DIR/$module"
    if [[ ! -f "$module_path" ]]; then
      echo "Missing module file: $module_path" >&2
      exit 1
    fi

    echo
    echo "// ---- $module ----"
    sed -E \
      -e '/^[[:space:]]*import[[:space:]]+/d' \
      -e 's/^[[:space:]]*export[[:space:]]+//' \
      "$module_path"
  done

  echo
  echo "// ---- mediarr-card.main.js ----"
  sed -E '/^[[:space:]]*import[[:space:]]+/d' "$SOURCE_MAIN"
} > "$TMP_FILE"

mv "$TMP_FILE" "$OUTPUT_FILE"
echo "Built $OUTPUT_FILE"
